Repository CSC-256-Group-Project-9/group-9-webapp, pull requests merged in 2023-10, with the labels that each got.

#4 Added Endpoints Page
  .gitignore
  app.py
  static/css/main.css
  templates/base.html
  templates/endpoints.html
Labels: documentation

#6 fix: java id
  templates/testing.html
Labels: bug

#8 added updates from unofficial hosted to this repo
  .gitignore
  .vercel/README.txt
  .vercel/project.json
  static/css/main.css
  templates/testing.html
  vercel.json
Labels: enhancement
